AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template deploys a demo lambda'
Parameters:
  EnvName:
    Type: String
    Description: Name of an environment. 'dev', 'staging', 'prod' and any name.
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.
    Default: dev

Resources:

  # Common Lambda Role
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "lambda-role-example"
      Description: "Role assigned to lambdas"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: '*'

  # Lambda
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "demo-lambda"
      Description: "demo lambda"
      Code:
        ZipFile: |
          def my_handler(event, context):
            message = 'Hello Lambda World!'
            return message
      Handler: lambda.handler
      Runtime: python3.9
      Timeout: 900
      Role: !GetAtt LambdaRole.Arn
      PackageType: Zip
      MemorySize: 128
